version: '3'

services:
  app:
    container_name: rewardchain-backend
    build: 
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - 3200:4200
    tty: true
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./backend_app
        target: /backend_app
    networks:
      - mychain-network
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    container_name: mysql80
    platform: linux/arm64
    restart: always
    ports:
      - 3306:3306
    env_file:
      - mysql.env
    healthcheck:   # ヘルスチェックの追加
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 5s
      retries: 6
      start_period: 30s
    networks:
      - mychain-network
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      # 設定ファイルディレクトリにマウントする
      - ./mysql/conf.d:/etc/mysql/conf.d
      # DB初期化ディレクトリにマウントする
      - ./mysql/init.d:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64
    container_name: phpmyadmin
    restart: always
    networks:
      - mychain-network
    depends_on:
      - db
    ports:
      - 9090:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions


volumes:
  mysql_data:

networks:
  mychain-network:
    driver: bridge