services:
  app:
    container_name: rewardchain-backend
    build: 
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - 3200:4200
    tty: true
    volumes:
      - type: bind
        source: ./backend_app
        target: /backend_app
    # environment:
    #   - WATCHPACK_POLLING=true

    dns:
      - 8.8.8.8
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    #network_mode: 'host'
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db
    # restart: always
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mysql:9.0
    container_name: mysql90
    restart: always
    ports:
      - '3006:3306'
    env_file:
      - mysql.env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 9090:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions