FROM --platform=linux/amd64 mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
# FROM --platform=linux/amd64 alpine/mysql:15.1

RUN su node -c "npm install -g npm@10.8.3"
# RUN su node -c "apk add --no-cache alpine-sdk \
#     mysql-client \
#     mysql-dev \
#     build-base \
#     tzdata"