volumes:
  mysql_data:

networks:
  mychain-network:
    name: mychain-network

services:
  app:
    container_name: rewardchain-backend
    build: 
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - 3200:4200
    tty: true
    volumes:
      - type: bind
        source: ./backend_app
        target: /backend_app
    # environment:
    #   - WATCHPACK_POLLING=true

    # dns:
    #   - 8.8.8.8
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    networks:
      - mychain-network
    # network_mode: 'host'
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: bridge
    # network_mode: service:db
    # restart: always
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    dns:
      - 8.8.8.8
      - 8.8.4.4
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql80
    restart: always
    ports:
      - '3306:3306'
    env_file:
      - mysql.env
    networks:
      - mychain-network
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    # network_mode: service:app
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    networks:
      - mychain-network
    depends_on:
      - db
    ports:
      - 9090:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
